# Generated by Django 6.0.2 on 2026-03-02 20:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('folio', models.CharField(max_length=50, unique=True, verbose_name='Folio')),
                ('id_cat_tramite', models.IntegerField(verbose_name='ID Catálogo Trámite')),
                (
                    'id_cat_estatus',
                    models.IntegerField(default=101, verbose_name='ID Catálogo Estatus'),
                ),
                (
                    'id_cat_perito',
                    models.IntegerField(blank=True, null=True, verbose_name='ID Perito'),
                ),
                (
                    'clave_catastral',
                    models.CharField(
                        blank=True, max_length=16, null=True, verbose_name='Clave Catastral'
                    ),
                ),
                (
                    'es_propietario',
                    models.BooleanField(default=True, verbose_name='Es Propietario'),
                ),
                (
                    'nom_sol',
                    models.CharField(max_length=200, verbose_name='Nombre del Solicitante'),
                ),
                (
                    'tel_sol',
                    models.CharField(blank=True, max_length=16, null=True, verbose_name='Teléfono'),
                ),
                (
                    'correo_sol',
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name='Correo Electrónico'
                    ),
                ),
                (
                    'importe_total',
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name='Importe Total',
                    ),
                ),
                ('pagado', models.BooleanField(default=False, verbose_name='Pagado')),
                (
                    'tipo',
                    models.CharField(blank=True, max_length=120, null=True, verbose_name='Tipo'),
                ),
                (
                    'observacion',
                    models.TextField(blank=True, null=True, verbose_name='Observación'),
                ),
                (
                    'urgente',
                    models.BooleanField(
                        blank=True, default=True, null=True, verbose_name='Urgente'
                    ),
                ),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
            ],
            options={
                'verbose_name': 'Trámite',
                'verbose_name_plural': 'Trámites',
                'db_table': 'tramite',
                'ordering': ('-creado',),
                'managed': True,
                'indexes': [
                    models.Index(fields=['folio'], name='tramite_folio_fb608e_idx'),
                    models.Index(
                        fields=['id_cat_estatus', '-creado'], name='tramite_id_cat__f4374b_idx'
                    ),
                    models.Index(
                        fields=['pagado', '-creado'], name='idx_tramite_estatus_no_pagado'
                    ),
                    models.Index(
                        condition=models.Q(('urgente', True)),
                        fields=['id', '-creado'],
                        name='idx_tramite_urgente',
                    ),
                    models.Index(
                        condition=models.Q(('urgente', True), ('pagado', False)),
                        fields=['id', '-creado'],
                        name='idx_tramite_urgente_no_pagado',
                    ),
                    models.Index(
                        condition=models.Q(('pagado', False)),
                        fields=['-urgente', 'id_cat_estatus', '-creado'],
                        name='idx_tramite_prioridad',
                    ),
                ],
            },
        ),
    ]
