# Generated by Django 6.0.2

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        # First: Create all catalog models (no FK dependencies)
        migrations.CreateModel(
            name='TramiteCatalogo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                (
                    'descripcion',
                    models.CharField(
                        blank=True, max_length=600, null=True, verbose_name='Descripción'
                    ),
                ),
                (
                    'area',
                    models.CharField(blank=True, max_length=80, null=True, verbose_name='Área'),
                ),
                (
                    'respuesta_dias',
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name='Respuesta en Días',
                    ),
                ),
                (
                    'pago_inicial',
                    models.BooleanField(blank=True, null=True, verbose_name='Pago Inicial'),
                ),
                (
                    'url',
                    models.CharField(blank=True, max_length=512, null=True, verbose_name='URL'),
                ),
                ('activo', models.BooleanField(null=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Catálogo Trámite',
                'verbose_name_plural': 'Catálogo Trámites',
                'db_table': 'cat_tramite',
                'ordering': ('nombre',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TramiteEstatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estatus', models.CharField(max_length=30, verbose_name='Estatus')),
                (
                    'responsable',
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name='Responsable'
                    ),
                ),
                (
                    'descripcion',
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name='Descripción'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Estatus de Trámite',
                'verbose_name_plural': 'Estatus de Trámites',
                'db_table': 'cat_estatus',
                'ordering': ('id',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Perito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                (
                    'paterno',
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name='Apellido Paterno'
                    ),
                ),
                (
                    'materno',
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name='Apellido Materno'
                    ),
                ),
                (
                    'nombre',
                    models.CharField(blank=True, max_length=90, null=True, verbose_name='Nombre'),
                ),
                (
                    'domicilio',
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name='Domicilio'
                    ),
                ),
                (
                    'colonia',
                    models.CharField(blank=True, max_length=120, null=True, verbose_name='Colonia'),
                ),
                (
                    'telefono',
                    models.CharField(blank=True, max_length=16, null=True, verbose_name='Teléfono'),
                ),
                (
                    'celular',
                    models.CharField(blank=True, max_length=16, null=True, verbose_name='Celular'),
                ),
                (
                    'correo',
                    models.CharField(blank=True, max_length=255, null=True, verbose_name='Correo'),
                ),
                (
                    'revalidacion',
                    models.DateField(blank=True, null=True, verbose_name='Revalidación'),
                ),
                (
                    'fecha_registro',
                    models.DateField(blank=True, null=True, verbose_name='Fecha de Registro'),
                ),
                ('rfc', models.CharField(blank=True, max_length=17, null=True, verbose_name='RFC')),
                ('estatus', models.BooleanField(verbose_name='Estatus')),
                (
                    'cedula',
                    models.CharField(blank=True, max_length=19, null=True, verbose_name='Cédula'),
                ),
            ],
            options={
                'verbose_name': 'Perito',
                'verbose_name_plural': 'Peritos',
                'db_table': 'cat_perito',
                'ordering': ('paterno', 'materno', 'nombre'),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('actividad', models.CharField(max_length=250, verbose_name='Actividad')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'db_table': 'cat_actividad',
                'ordering': ['actividad'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                (
                    'categoria',
                    models.CharField(
                        blank=True, max_length=120, null=True, verbose_name='Categoría'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'cat_categoria',
                'ordering': ['categoria'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Requisito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('requisito', models.CharField(max_length=480, verbose_name='Requisito')),
            ],
            options={
                'verbose_name': 'Requisito',
                'verbose_name_plural': 'Requisitos',
                'db_table': 'cat_requisito',
                'ordering': ['requisito'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=120, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipos',
                'db_table': 'cat_tipo',
                'ordering': ['tipo'],
                'managed': True,
            },
        ),
        # Second: Create Tramite (references TramiteCatalogo and Perito)
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('folio', models.CharField(max_length=50, unique=True, verbose_name='Folio')),
                (
                    'clave_catastral',
                    models.CharField(
                        blank=True, max_length=16, null=True, verbose_name='Clave Catastral'
                    ),
                ),
                (
                    'es_propietario',
                    models.BooleanField(default=True, verbose_name='Es Propietario'),
                ),
                (
                    'nom_sol',
                    models.CharField(max_length=200, verbose_name='Nombre del Solicitante'),
                ),
                (
                    'tel_sol',
                    models.CharField(blank=True, max_length=16, null=True, verbose_name='Teléfono'),
                ),
                (
                    'correo_sol',
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name='Correo Electrónico'
                    ),
                ),
                (
                    'importe_total',
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name='Importe Total',
                    ),
                ),
                ('pagado', models.BooleanField(default=False, verbose_name='Pagado')),
                (
                    'tipo',
                    models.CharField(blank=True, max_length=120, null=True, verbose_name='Tipo'),
                ),
                (
                    'observacion',
                    models.TextField(blank=True, null=True, verbose_name='Observación'),
                ),
                (
                    'urgente',
                    models.BooleanField(
                        blank=True, default=True, null=True, verbose_name='Urgente'
                    ),
                ),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                (
                    'tramite_catalogo',
                    models.ForeignKey(
                        db_column='id_cat_tramite',
                        on_delete=models.DO_NOTHING,
                        related_name='tramites',
                        to='tramites.tramitecatalogo',
                        verbose_name='Catálogo Trámite',
                    ),
                ),
                (
                    'perito',
                    models.ForeignKey(
                        blank=True,
                        db_column='id_cat_perito',
                        null=True,
                        on_delete=models.DO_NOTHING,
                        related_name='tramites',
                        to='tramites.perito',
                        verbose_name='Perito',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Trámite',
                'verbose_name_plural': 'Trámites',
                'db_table': 'tramite',
                'ordering': ('-creado',),
                'managed': True,
            },
        ),
        # Third: Create Actividades (references Tramite and TramiteEstatus)
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                (
                    'backoffice_user_id',
                    models.IntegerField(
                        blank=True, null=True, verbose_name='ID Usuario Backoffice'
                    ),
                ),
                (
                    'observacion',
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name='Observación'
                    ),
                ),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha/Hora')),
                (
                    'tramite',
                    models.ForeignKey(
                        db_column='id_tramite',
                        on_delete=models.CASCADE,
                        related_name='actividades',
                        to='tramites.tramite',
                        verbose_name='Trámite',
                    ),
                ),
                (
                    'estatus',
                    models.ForeignKey(
                        db_column='id_cat_estatus',
                        on_delete=models.RESTRICT,
                        related_name='actividades',
                        to='tramites.tramiteestatus',
                        verbose_name='Estatus',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Actividad de Trámite',
                'verbose_name_plural': 'Actividades de Trámite',
                'db_table': 'actividades',
                'ordering': ['-timestamp'],
                'managed': True,
            },
        ),
    ]
