# Generated by Django 6.0.4 on 2026-04-27 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('actividad', models.CharField(max_length=250, verbose_name='Actividad')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'db_table': 'cat_actividad',
                'ordering': ['actividad'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                (
                    'backoffice_user_id',
                    models.IntegerField(
                        blank=True, null=True, verbose_name='ID Usuario Backoffice'
                    ),
                ),
                (
                    'observacion',
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name='Observación'
                    ),
                ),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha/Hora')),
            ],
            options={
                'verbose_name': 'Actividad de Trámite',
                'verbose_name_plural': 'Actividades de Trámite',
                'db_table': 'actividades',
                'ordering': ['-timestamp'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                (
                    'categoria',
                    models.CharField(
                        blank=True, max_length=120, null=True, verbose_name='Categoría'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'cat_categoria',
                'ordering': ['categoria'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Perito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                (
                    'paterno',
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name='Apellido Paterno'
                    ),
                ),
                (
                    'materno',
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name='Apellido Materno'
                    ),
                ),
                (
                    'nombre',
                    models.CharField(blank=True, max_length=90, null=True, verbose_name='Nombre'),
                ),
                (
                    'domicilio',
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name='Domicilio'
                    ),
                ),
                (
                    'colonia',
                    models.CharField(blank=True, max_length=120, null=True, verbose_name='Colonia'),
                ),
                (
                    'telefono',
                    models.CharField(blank=True, max_length=16, null=True, verbose_name='Teléfono'),
                ),
                (
                    'celular',
                    models.CharField(blank=True, max_length=16, null=True, verbose_name='Celular'),
                ),
                (
                    'correo',
                    models.CharField(blank=True, max_length=255, null=True, verbose_name='Correo'),
                ),
                (
                    'revalidacion',
                    models.DateField(blank=True, null=True, verbose_name='Revalidación'),
                ),
                (
                    'fecha_registro',
                    models.DateField(blank=True, null=True, verbose_name='Fecha de Registro'),
                ),
                ('rfc', models.CharField(blank=True, max_length=17, null=True, verbose_name='RFC')),
                ('estatus', models.BooleanField(verbose_name='Estatus')),
                (
                    'cedula',
                    models.CharField(blank=True, max_length=19, null=True, verbose_name='Cédula'),
                ),
            ],
            options={
                'verbose_name': 'Perito',
                'verbose_name_plural': 'Peritos',
                'db_table': 'cat_perito',
                'ordering': ('paterno', 'materno', 'nombre'),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Requisito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('requisito', models.CharField(max_length=480, verbose_name='Requisito')),
            ],
            options={
                'verbose_name': 'Requisito',
                'verbose_name_plural': 'Requisitos',
                'db_table': 'cat_requisito',
                'ordering': ['requisito'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=120, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipos',
                'db_table': 'cat_tipo',
                'ordering': ['tipo'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('folio', models.CharField(help_text='Folio del trámite', max_length=50)),
                ('tramite_id', models.IntegerField()),
                ('tramite_nombre', models.CharField(help_text='Tipo de trámite', max_length=255)),
                ('tramite_categoria_id', models.IntegerField(blank=True, null=True)),
                (
                    'tramite_categoria_nombre',
                    models.CharField(blank=True, help_text='Categoría', max_length=255, null=True),
                ),
                ('tramite_tipo_cobro_id', models.IntegerField(blank=True, null=True)),
                (
                    'tramite_tipo_cobro_nombre',
                    models.CharField(
                        blank=True, help_text='Tipo de cobro', max_length=100, null=True
                    ),
                ),
                (
                    'clave_catastral',
                    models.CharField(
                        blank=True, help_text='Clave catastral', max_length=100, null=True
                    ),
                ),
                (
                    'es_propietario',
                    models.BooleanField(
                        help_text='Indica si el solicitante es el propietario del inmueble'
                    ),
                ),
                (
                    'importe_total',
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text='Importe total del trámite',
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    'urgente',
                    models.BooleanField(
                        help_text='Indica si el trámite es urgente', verbose_name='Urgente'
                    ),
                ),
                (
                    'solicitante_nombre',
                    models.CharField(
                        blank=True, help_text='Nombre del solicitante', max_length=200, null=True
                    ),
                ),
                (
                    'solicitante_telefono',
                    models.CharField(
                        blank=True, help_text='Teléfono del solicitante', max_length=20, null=True
                    ),
                ),
                (
                    'solicitante_correo',
                    models.CharField(
                        blank=True, help_text='Correo del solicitante', max_length=100, null=True
                    ),
                ),
                (
                    'solicitante_comentario',
                    models.TextField(blank=True, help_text='Comentario del solicitante', null=True),
                ),
                ('perito_id', models.IntegerField(blank=True, null=True)),
                (
                    'perito_nombre',
                    models.CharField(
                        blank=True, help_text='Nombre del perito', max_length=200, null=True
                    ),
                ),
                ('ultima_actividad_estatus_id', models.IntegerField(blank=True, null=True)),
                (
                    'ultima_actividad_estatus',
                    models.CharField(
                        blank=True,
                        help_text='Estado de la última actividad',
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    'ultima_actividad_responsable',
                    models.CharField(
                        blank=True,
                        help_text='Responsable de la última actividad',
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    'ultima_actividad_descripcion',
                    models.TextField(
                        blank=True, help_text='Descripción de la última actividad', null=True
                    ),
                ),
                (
                    'ultima_actividad_observacion',
                    models.TextField(
                        blank=True, help_text='Observación de la última actividad', null=True
                    ),
                ),
                ('asignado_user_id', models.IntegerField(blank=True, null=True)),
                (
                    'asignado_username',
                    models.CharField(
                        blank=True,
                        help_text='Nombre de usuario del analista asignado',
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    'asignado_nombre',
                    models.CharField(
                        blank=True,
                        help_text='Nombre del analista asignado',
                        max_length=150,
                        null=True,
                    ),
                ),
                ('asignado_group_id', models.IntegerField(blank=True, null=True)),
                (
                    'asignado_rol',
                    models.CharField(
                        blank=True, help_text='Rol del analista asignado', max_length=150, null=True
                    ),
                ),
                (
                    'creado',
                    models.DateTimeField(
                        help_text='Fecha y hora de creación del trámite',
                        verbose_name='Fecha de creación',
                    ),
                ),
                (
                    'actualizado',
                    models.DateTimeField(
                        blank=True,
                        help_text='Fecha y hora de la última actualización del trámite',
                        null=True,
                        verbose_name='Fecha de actualización',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Lista de Trámites',
                'verbose_name_plural': 'Trámites',
                'db_table': 'v_tramites_unificado',
                'ordering': ('-creado', 'urgente'),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TramiteCatalogo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                (
                    'descripcion',
                    models.CharField(
                        blank=True, max_length=600, null=True, verbose_name='Descripción'
                    ),
                ),
                (
                    'area',
                    models.CharField(blank=True, max_length=80, null=True, verbose_name='Área'),
                ),
                (
                    'respuesta_dias',
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name='Respuesta en Días',
                    ),
                ),
                (
                    'pago_inicial',
                    models.BooleanField(blank=True, null=True, verbose_name='Pago Inicial'),
                ),
                (
                    'url',
                    models.CharField(blank=True, max_length=512, null=True, verbose_name='URL'),
                ),
                ('activo', models.BooleanField(null=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Catálogo Trámite',
                'verbose_name_plural': 'Catálogo Trámites',
                'db_table': 'cat_tramite',
                'ordering': ('nombre',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TramiteCatalogoActividad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Relación Trámite-Actividad',
                'verbose_name_plural': 'Relaciones Trámite-Actividad',
                'db_table': 'rel_tmt_actividad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TramiteCatalogoCategoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Relación Trámite-Categoría',
                'verbose_name_plural': 'Relaciones Trámite-Categoría',
                'db_table': 'rel_tmt_categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TramiteCatalogoRequisito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Relación Trámite-Requisito-Categoría',
                'verbose_name_plural': 'Relaciones Trámite-Requisito-Categoría',
                'db_table': 'rel_tmt_cate_req',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TramiteCatalogoTipoRequisito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Relación Tipo-Trámite-Requisito',
                'verbose_name_plural': 'Relaciones Tipo-Trámite-Requisito',
                'db_table': 'rel_tmt_tipo_req',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TramiteEstatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estatus', models.CharField(max_length=30, verbose_name='Estatus')),
                (
                    'responsable',
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name='Responsable'
                    ),
                ),
                (
                    'descripcion',
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name='Descripción'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Estatus de Trámite',
                'verbose_name_plural': 'Estatus de Trámites',
                'db_table': 'cat_estatus',
                'ordering': ('id',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Buzon',
            fields=[],
            options={
                'verbose_name': 'Mis trámites',
                'verbose_name_plural': 'Buzón de trámites',
                'ordering': ('-creado', '-urgente'),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tramites.tramite',),
        ),
        migrations.CreateModel(
            name='Disponible',
            fields=[],
            options={
                'verbose_name': 'Trámite disponible para autoasignación',
                'verbose_name_plural': 'Trámites disponibles',
                'ordering': ('-creado', '-urgente'),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tramites.tramite',),
        ),
    ]
