# Generated by Django 6.0.2 on 2026-03-11 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tramite',
            options={'managed': False, 'ordering': ('-creado',), 'verbose_name': 'Trámite', 'verbose_name_plural': 'Trámites'},
        ),
    ]
