# Generated by Django 6.0.2 on 2026-04-13 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividades',
            options={'managed': False, 'ordering': ['-timestamp'], 'verbose_name': 'Actividad de Trámite', 'verbose_name_plural': 'Actividades de Trámite'},
        ),
        migrations.AlterModelOptions(
            name='tramite',
            options={'managed': False, 'ordering': ('-creado',), 'verbose_name': 'Trámite', 'verbose_name_plural': 'Trámites'},
        ),
        migrations.CreateModel(
            name='TramiteCatalogoActividad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('actividad', models.ForeignKey(db_column='id_cat_actividad', on_delete=django.db.models.deletion.DO_NOTHING, related_name='tramites_catalogo', to='tramites.actividad', verbose_name='Actividad')),
                ('tramite_catalogo', models.ForeignKey(db_column='id_cat_tramite', on_delete=django.db.models.deletion.DO_NOTHING, related_name='actividades', to='tramites.tramitecatalogo', verbose_name='Catálogo Trámite')),
            ],
            options={
                'verbose_name': 'Relación Trámite-Actividad',
                'verbose_name_plural': 'Relaciones Trámite-Actividad',
                'db_table': 'rel_tmt_actividad',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TramiteCatalogoCategoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.ForeignKey(db_column='id_cat_categoria', on_delete=django.db.models.deletion.DO_NOTHING, related_name='tramites_catalogo', to='tramites.categoria', verbose_name='Categoría')),
                ('tramite_catalogo', models.ForeignKey(db_column='id_cat_tramite', on_delete=django.db.models.deletion.DO_NOTHING, related_name='categorias', to='tramites.tramitecatalogo', verbose_name='Catálogo Trámite')),
            ],
            options={
                'verbose_name': 'Relación Trámite-Categoría',
                'verbose_name_plural': 'Relaciones Trámite-Categoría',
                'db_table': 'rel_tmt_categoria',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TramiteCatalogoRequisito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.ForeignKey(blank=True, db_column='id_cat_categoria', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='requisitos_por_tramite', to='tramites.categoria', verbose_name='Categoría')),
                ('requisito', models.ForeignKey(db_column='id_cat_requisito', on_delete=django.db.models.deletion.DO_NOTHING, related_name='tramites_catalogo', to='tramites.requisito', verbose_name='Requisito')),
                ('tramite_catalogo', models.ForeignKey(db_column='id_cat_tramite', on_delete=django.db.models.deletion.DO_NOTHING, related_name='requisitos', to='tramites.tramitecatalogo', verbose_name='Catálogo Trámite')),
            ],
            options={
                'verbose_name': 'Relación Trámite-Requisito-Categoría',
                'verbose_name_plural': 'Relaciones Trámite-Requisito-Categoría',
                'db_table': 'rel_tmt_cate_req',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TramiteCatalogoTipoRequisito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('requisito', models.ForeignKey(db_column='id_cat_requisito', on_delete=django.db.models.deletion.DO_NOTHING, related_name='tipos_por_tramite', to='tramites.requisito', verbose_name='Requisito')),
                ('tipo', models.ForeignKey(db_column='id_cat_tipo', on_delete=django.db.models.deletion.DO_NOTHING, related_name='requisitos_por_tramite', to='tramites.tipo', verbose_name='Tipo')),
                ('tramite_catalogo', models.ForeignKey(db_column='id_cat_tramite', on_delete=django.db.models.deletion.DO_NOTHING, related_name='tipos_requisito', to='tramites.tramitecatalogo', verbose_name='Catálogo Trámite')),
            ],
            options={
                'verbose_name': 'Relación Tipo-Trámite-Requisito',
                'verbose_name_plural': 'Relaciones Tipo-Trámite-Requisito',
                'db_table': 'rel_tmt_tipo_req',
                'managed': True,
            },
        ),
    ]
