# Generated by Django 6.0.2 on 2026-04-15 01:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0002_alter_actividades_options_alter_tramite_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionTramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tramite_id', models.IntegerField(verbose_name='ID Trámite')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Asignación')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observación')),
                ('analista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_recibidas', to=settings.AUTH_USER_MODEL, verbose_name='Analista')),
                ('asignado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Asignado Por')),
            ],
            options={
                'verbose_name': 'Asignación de Trámite',
                'verbose_name_plural': 'Asignaciones de Trámites',
                'db_table': 'asignacion_tramite',
                'ordering': ('-fecha_asignacion',),
                'indexes': [models.Index(fields=['analista'], name='asignacion__analist_0b1938_idx'), models.Index(fields=['tramite_id'], name='asignacion__tramite_347a5d_idx')],
                'constraints': [models.UniqueConstraint(fields=('tramite_id',), name='una_sola_asignacion_por_tramite', violation_error_message='Este trámite ya está asignado a otro analista')],
            },
        ),
    ]
