# Generated by Django 6.0.4 on 2026-08-13 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0002_cerrado'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnDiligencia',
            fields=[
            ],
            options={
                'verbose_name': 'Trámite en diligencia',
                'verbose_name_plural': 'Trámites en diligencia',
                'ordering': ('-creado', '-urgente'),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tramites.tramite',),
        ),
    ]
