# Generated by Django 6.0.2 on 2026-03-02 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_tramite', models.IntegerField(verbose_name='ID Trámite')),
                ('id_cat_actividad', models.IntegerField(verbose_name='ID Catálogo Actividad')),
                ('id_cat_estatus', models.IntegerField(verbose_name='ID Catálogo Estatus')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha Fin')),
                ('id_cat_usuario', models.IntegerField(verbose_name='ID Usuario')),
                ('secuencia', models.IntegerField(verbose_name='Secuencia')),
                (
                    'observacion',
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name='Observación'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'db_table': 'actividades',
                'ordering': ['-secuencia'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CatActividad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('actividad', models.CharField(max_length=250, verbose_name='Actividad')),
            ],
            options={
                'verbose_name': 'Catálogo Actividad',
                'verbose_name_plural': 'Catálogo Actividades',
                'db_table': 'cat_actividad',
                'ordering': ['actividad'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CatCategoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                (
                    'categoria',
                    models.CharField(
                        blank=True, max_length=120, null=True, verbose_name='Categoría'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Catálogo Categoría',
                'verbose_name_plural': 'Catálogo Categorías',
                'db_table': 'cat_categoria',
                'ordering': ['categoria'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CatEstatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estatus', models.CharField(max_length=30, verbose_name='Estatus')),
                (
                    'responsable',
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name='Responsable'
                    ),
                ),
                (
                    'descripcion',
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name='Descripción'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Catálogo Estatus',
                'verbose_name_plural': 'Catálogo Estatus',
                'db_table': 'cat_estatus',
                'ordering': ['id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CatInciso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('inciso', models.IntegerField(verbose_name='Inciso')),
                (
                    'descripcion',
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name='Descripción'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Catálogo Inciso',
                'verbose_name_plural': 'Catálogo Incisos',
                'db_table': 'cat_inciso',
                'ordering': ['inciso'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CatPerito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                (
                    'paterno',
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name='Apellido Paterno'
                    ),
                ),
                (
                    'materno',
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name='Apellido Materno'
                    ),
                ),
                (
                    'nombre',
                    models.CharField(blank=True, max_length=90, null=True, verbose_name='Nombre'),
                ),
                (
                    'domicilio',
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name='Domicilio'
                    ),
                ),
                (
                    'colonia',
                    models.CharField(blank=True, max_length=120, null=True, verbose_name='Colonia'),
                ),
                (
                    'telefono',
                    models.CharField(blank=True, max_length=16, null=True, verbose_name='Teléfono'),
                ),
                (
                    'celular',
                    models.CharField(blank=True, max_length=16, null=True, verbose_name='Celular'),
                ),
                (
                    'correo',
                    models.CharField(blank=True, max_length=255, null=True, verbose_name='Correo'),
                ),
                (
                    'revalidacion',
                    models.DateField(blank=True, null=True, verbose_name='Revalidación'),
                ),
                (
                    'fecha_registro',
                    models.DateField(blank=True, null=True, verbose_name='Fecha de Registro'),
                ),
                ('rfc', models.CharField(blank=True, max_length=17, null=True, verbose_name='RFC')),
                ('estatus', models.BooleanField(verbose_name='Estatus')),
                (
                    'cedula',
                    models.CharField(blank=True, max_length=19, null=True, verbose_name='Cédula'),
                ),
            ],
            options={
                'verbose_name': 'Catálogo Perito',
                'verbose_name_plural': 'Catálogo Peritos',
                'db_table': 'cat_perito',
                'ordering': ['paterno', 'materno', 'nombre'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CatRequisito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('requisito', models.CharField(max_length=480, verbose_name='Requisito')),
            ],
            options={
                'verbose_name': 'Catálogo Requisito',
                'verbose_name_plural': 'Catálogo Requisitos',
                'db_table': 'cat_requisito',
                'ordering': ['requisito'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CatTipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=120, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Catálogo Tipo',
                'verbose_name_plural': 'Catálogo Tipos',
                'db_table': 'cat_tipo',
                'ordering': ['tipo'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CatTramite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                (
                    'descripcion',
                    models.CharField(
                        blank=True, max_length=600, null=True, verbose_name='Descripción'
                    ),
                ),
                (
                    'area',
                    models.CharField(blank=True, max_length=80, null=True, verbose_name='Área'),
                ),
                (
                    'respuesta_dias',
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name='Respuesta en Días',
                    ),
                ),
                (
                    'pago_inicial',
                    models.BooleanField(blank=True, null=True, verbose_name='Pago Inicial'),
                ),
                (
                    'url',
                    models.CharField(blank=True, max_length=512, null=True, verbose_name='URL'),
                ),
                ('activo', models.BooleanField(null=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Catálogo Trámite',
                'verbose_name_plural': 'Catálogo Trámites',
                'db_table': 'cat_tramite',
                'ordering': ['nombre'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cobro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('concepto', models.CharField(max_length=250, verbose_name='Concepto')),
                (
                    'importe',
                    models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Importe'),
                ),
                ('inciso', models.IntegerField(blank=True, null=True, verbose_name='Inciso')),
                ('id_tramite', models.IntegerField(verbose_name='ID Trámite')),
            ],
            options={
                'verbose_name': 'Cobro',
                'verbose_name_plural': 'Cobros',
                'db_table': 'cobro',
                'ordering': ['-id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RelTmtActividad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_cat_tramite', models.IntegerField(verbose_name='ID Catálogo Trámite')),
                ('id_cat_actividad', models.IntegerField(verbose_name='ID Actividad')),
            ],
            options={
                'verbose_name': 'Relación Trámite-Actividad',
                'verbose_name_plural': 'Relaciones Trámite-Actividad',
                'db_table': 'rel_tmt_actividad',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RelTmtCategoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_cat_tramite', models.IntegerField(verbose_name='ID Catálogo Trámite')),
                ('id_cat_categoria', models.IntegerField(verbose_name='ID Categoría')),
            ],
            options={
                'verbose_name': 'Relación Trámite-Categoría',
                'verbose_name_plural': 'Relaciones Trámite-Categoría',
                'db_table': 'rel_tmt_categoria',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RelTmtCateReq',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_cat_tramite', models.IntegerField(verbose_name='ID Catálogo Trámite')),
                ('id_cat_requisito', models.IntegerField(verbose_name='ID Catálogo Requisito')),
                (
                    'id_cat_categoria',
                    models.IntegerField(blank=True, null=True, verbose_name='ID Categoría'),
                ),
            ],
            options={
                'verbose_name': 'Relación Trámite-Requisito-Categoría',
                'verbose_name_plural': 'Relaciones Trámite-Requisito-Categoría',
                'db_table': 'rel_tmt_cate_req',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RelTmtInciso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_cat_inciso', models.IntegerField(verbose_name='ID Inciso')),
                ('id_cat_tramite', models.IntegerField(verbose_name='ID Catálogo Trámite')),
            ],
            options={
                'verbose_name': 'Relación Inciso-Trámite',
                'verbose_name_plural': 'Relaciones Inciso-Trámite',
                'db_table': 'rel_tmt_inciso',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RelTmtTipoReq',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_cat_tipo', models.IntegerField(verbose_name='ID Tipo')),
                ('id_cat_tramite', models.IntegerField(verbose_name='ID Catálogo Trámite')),
                ('id_cat_requisito', models.IntegerField(verbose_name='ID Catálogo Requisito')),
            ],
            options={
                'verbose_name': 'Relación Tipo-Trámite-Requisito',
                'verbose_name_plural': 'Relaciones Tipo-Trámite-Requisito',
                'db_table': 'rel_tmt_tipo_req',
                'managed': True,
            },
        ),
    ]
