# Generated by Django 6.0.2 on 2026-03-02 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Costo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_tramite', models.IntegerField(verbose_name='ID Trámite')),
                ('axo', models.IntegerField(default=2020, verbose_name='Año')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                (
                    'formula',
                    models.CharField(blank=True, max_length=255, null=True, verbose_name='Fórmula'),
                ),
                (
                    'cant_umas',
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name='Cantidad de UMA',
                    ),
                ),
                (
                    'rango_ini',
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name='Rango Inicial',
                    ),
                ),
                (
                    'rango_fin',
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name='Rango Final',
                    ),
                ),
                ('inciso', models.IntegerField(blank=True, null=True, verbose_name='Inciso')),
                (
                    'fomento',
                    models.BooleanField(
                        blank=True, default=True, null=True, verbose_name='Fomento'
                    ),
                ),
                (
                    'cruz_roja',
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name='Cruz Roja',
                    ),
                ),
                (
                    'bomberos',
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name='Bomberos',
                    ),
                ),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('id_usuario', models.IntegerField(verbose_name='ID Usuario')),
                ('fecha_actualiza', models.DateField(verbose_name='Fecha de Actualización')),
                (
                    'observacion',
                    models.CharField(
                        blank=True, max_length=600, null=True, verbose_name='Observación'
                    ),
                ),
                ('id_tipo', models.IntegerField(blank=True, null=True, verbose_name='ID Tipo')),
            ],
            options={
                'verbose_name': 'Costo',
                'verbose_name_plural': 'Costos',
                'db_table': 'costo',
                'ordering': ['id_tramite', 'rango_ini'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Uma',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                (
                    'valor',
                    models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Valor'),
                ),
            ],
            options={
                'verbose_name': 'UMA',
                'verbose_name_plural': 'UMAs',
                'db_table': 'uma',
                'managed': True,
            },
        ),
    ]
