"""Django Admin configuration for bitacora app.

Provides read-only admin interface for the audit log (bitacora).
All entries are automatically generated by the system and should not be modified manually.
"""

from django.contrib import admin
from django.utils.html import format_html

from bitacora.models import Bitacora
from core.admin import BaseModelAdmin, ReadOnlyModelAdmin


@admin.register(Bitacora)
class BitacoraAdmin(ReadOnlyModelAdmin, BaseModelAdmin):
    """Admin interface for Bitacora model (read-only).

    This model is automatically populated by the system and should not be modified manually.
    """

    # List display configuration
    list_display = (
        "fecha",
        "usuario_sis",
        "tipo_mov_badge",
        "usuario_pc",
        "maquina",
        "observaciones",
    )

    # List filtering
    list_filter = ("tipo_mov", "fecha", "usuario_sis")

    # Search fields
    search_fields = (
        "usuario_sis",
        "usuario_pc",
        "maquina",
        "val_anterior",
        "val_nuevo",
        "observaciones",
    )

    # Ordering
    ordering = ("-fecha", "-id")

    # Pagination
    list_per_page = 50
    list_max_show_all = 200

    # Date hierarchy
    date_hierarchy = "fecha"

    # Fieldsets for the detail view
    fieldsets = (
        (
            "Información del Movimiento",
            {
                "fields": (
                    "fecha",
                    "tipo_mov",
                    "usuario_sis",
                    "usuario_pc",
                    "maquina",
                ),
            },
        ),
        (
            "Valores",
            {
                "fields": (
                    "val_anterior",
                    "val_nuevo",
                ),
                "classes": ("collapse",),
            },
        ),
        (
            "Observaciones",
            {
                "fields": ("observaciones",),
            },
        ),
    )

    # All fields are read-only
    readonly_fields = (
        "id",
        "fecha",
        "tipo_mov",
        "usuario_sis",
        "usuario_pc",
        "maquina",
        "val_anterior",
        "val_nuevo",
        "observaciones",
    )

    # No delete permission for audit log
    def has_delete_permission(self, request, obj=None):
        """Disable delete permission for audit log."""
        return False

    # Custom display methods
    def tipo_mov_badge(self, obj):
        """Display tipo_mov with color coding."""
        tipo = obj.tipo_mov.upper()

        if tipo == "INSERT":
            badge_class = "badge-insert"
        elif tipo == "UPDATE":
            badge_class = "badge-update"
        elif tipo == "DELETE":
            badge_class = "badge-delete"
        else:
            badge_class = "badge-otro"

        return format_html('<span class="badge {}">{}</span>', badge_class, tipo)

    tipo_mov_badge.short_description = "Tipo de Movimiento"
    tipo_mov_badge.admin_order_field = "tipo_mov"
    tipo_mov_badge.allow_tags = True

    # Custom change list view with statistics
    def changelist_view(self, request, extra_context=None):
        """Add statistics to change list view."""
        extra_context = extra_context or {}

        # Calculate statistics
        total_movimientos = Bitacora.objects.count()
        inserts = Bitacora.objects.filter(tipo_mov="INSERT").count()
        updates = Bitacora.objects.filter(tipo_mov="UPDATE").count()
        deletes = Bitacora.objects.filter(tipo_mov="DELETE").count()

        extra_context.update(
            {
                "total_movimientos": total_movimientos,
                "movimientos_insert": inserts,
                "movimientos_update": updates,
                "movimientos_delete": deletes,
            }
        )

        return super().changelist_view(request, extra_context)
