"""Django Admin configuration for bitacora app.

Provides read-only admin interface for the audit log (bitacora).
All entries are automatically generated by the system and should not be modified manually.
"""

from django.conf import settings
from django.contrib import admin
from django.utils.html import format_html

from bitacora.models import Bitacora
from core.admin import BaseModelAdmin, ReadOnlyModelAdmin


@admin.register(Bitacora)
class BitacoraAdmin(ReadOnlyModelAdmin):
    """Admin interface for Bitacora model (read-only)."""

    list_display = (
        'id',
        'usuario_sis',
        'tipo_mov',
        'usuario_pc',
        'fecha',
        'maquina',
        'observaciones',
    )

    list_filter = ('fecha', 'tipo_mov')
    search_fields = ('usuario_sis', 'tipo_mov', 'observaciones')
    ordering = ('-fecha',)

    fieldsets = (
        (
            'Información del Movimiento',
            {
                'fields': (
                    'usuario_sis',
                    'tipo_mov',
                    'usuario_pc',
                    'fecha',
                    'maquina',
                ),
            },
        ),
        (
            'Valores',
            {
                'fields': (
                    'val_anterior',
                    'val_nuevo',
                ),
            },
        ),
        (
            'Información Adicional',
            {
                'fields': ('observaciones',),
            },
        ),
    )
