# Generated by Django 6.0.2 on 2026-04-06 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tramites', '0002_alter_tramite_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionTramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analista_id', models.IntegerField(verbose_name='ID Analista')),
                ('asignado_por_id', models.IntegerField(blank=True, null=True, verbose_name='ID Asignado Por')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Asignación')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observación')),
                ('tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tramites.tramite', verbose_name='Trámite')),
            ],
            options={
                'verbose_name': 'Asignación de Trámite',
                'verbose_name_plural': 'Asignaciones de Trámites',
                'db_table': 'asignacion_tramite',
                'ordering': ('-fecha_asignacion',),
                'indexes': [models.Index(fields=['analista_id'], name='asignacion__analist_0b1938_idx'), models.Index(fields=['tramite'], name='asignacion__tramite_347a5d_idx')],
                'constraints': [models.UniqueConstraint(fields=('tramite',), name='una_sola_asignacion_por_tramite', violation_error_message='Este trámite ya está asignado a otro analista')],
            },
        ),
    ]
