"""
Models for tramite app.

Only contains the Tramite model as per schema definition.
Note: This is a mapping to the external SQL schema - do NOT use Django migrations.
"""

from django.db import models

from catalogos.models import CatEstatus, CatTramite


class Tramite(models.Model):
    """Main model for tramites.

    Maps to SQL table 'tramite' from external schema.
    The folio is auto-generated by SQL triggers.
    """

    class Meta:
        managed = False
        db_table = "tramite"
        verbose_name = "Trámite"
        verbose_name_plural = "Trámites"
        ordering = ("-creado", )
        indexes = (
            models.Index(fields=["folio"]),
            models.Index(fields=["id_cat_estatus", "-creado"]),
            models.Index(
                fields=["pagado", "-creado"], name="idx_tramite_estatus_no_pagado"
            ),
            models.Index(
                fields=["id", "-creado"],
                condition=models.Q(urgente=True),
                name="idx_tramite_urgente",
            ),
            models.Index(
                fields=["id", "-creado"],
                condition=models.Q(urgente=True) & models.Q(pagado=False),
                name="idx_tramite_urgente_no_pagado",
            ),
            models.Index(
                fields=["-urgente", "id_cat_estatus", "-creado"],
                condition=models.Q(pagado=False),
                name="idx_tramite_prioridad",
            ),
        )

    # Primary key
    id = models.AutoField(primary_key=True)

    # Unique folio (auto-generated by SQL trigger)
    folio = models.CharField(max_length=50, unique=True, verbose_name="Folio")

    # Foreign keys to catalog tables (stored as IntegerField)
    id_cat_tramite = models.IntegerField(verbose_name="ID Catálogo Trámite")
    id_cat_estatus = models.IntegerField(
        default=101, verbose_name="ID Catálogo Estatus"
    )
    id_cat_perito = models.IntegerField(null=True, blank=True, verbose_name="ID Perito")

    # Solicitant information
    clave_catastral = models.CharField(
        max_length=16, blank=True, null=True, verbose_name="Clave Catastral"
    )
    es_propietario = models.BooleanField(default=True, verbose_name="Es Propietario")
    nom_sol = models.CharField(max_length=200, verbose_name="Nombre del Solicitante")
    tel_sol = models.CharField(
        max_length=16, blank=True, null=True, verbose_name="Teléfono"
    )
    correo_sol = models.CharField(
        max_length=255, blank=True, null=True, verbose_name="Correo Electrónico"
    )

    # Financial information
    importe_total = models.DecimalField(
        max_digits=12,
        decimal_places=2,
        null=True,
        blank=True,
        verbose_name="Importe Total",
    )
    pagado = models.BooleanField(default=False, verbose_name="Pagado")

    # Additional information
    tipo = models.CharField(max_length=120, blank=True, null=True, verbose_name="Tipo")
    observacion = models.TextField(blank=True, null=True, verbose_name="Observación")
    urgente = models.BooleanField(default=True, verbose_name="Urgente")

    # Timestamps (managed by SQL triggers)
    creado = models.DateTimeField(auto_now_add=True, verbose_name="Creado")
    modificado = models.DateTimeField(auto_now=True, verbose_name="Modificado")

    def __str__(self) -> str:
        return f"{self.folio}"

    @property
    def estatus_display(self) -> str:
        """Get display name for estatus from cat_estatus."""
        try:
            estatus = CatEstatus.objects.get(id=self.id_cat_estatus)
            return estatus.estatus
        except CatEstatus.DoesNotExist:
            return f"ID {self.id_cat_estatus}"

    @property
    def tramite_display(self) -> str:
        """Get display name for tramite from cat_tramite."""
        try:
            tramite = CatTramite.objects.get(id=self.id_cat_tramite)
            return tramite.nombre
        except CatTramite.DoesNotExist:
            return f"ID {self.id_cat_tramite}"
