# Generated by Django 6.0.2 on 2026-03-02 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario_sis', models.CharField(max_length=20, verbose_name='Usuario Sistema')),
                ('tipo_mov', models.CharField(max_length=20, verbose_name='Tipo de Movimiento')),
                ('usuario_pc', models.CharField(max_length=20, verbose_name='Usuario PC')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                (
                    'maquina',
                    models.CharField(blank=True, max_length=20, null=True, verbose_name='Máquina'),
                ),
                (
                    'val_anterior',
                    models.CharField(
                        blank=True, max_length=120, null=True, verbose_name='Valor Anterior'
                    ),
                ),
                (
                    'val_nuevo',
                    models.CharField(
                        blank=True, max_length=120, null=True, verbose_name='Valor Nuevo'
                    ),
                ),
                (
                    'observaciones',
                    models.CharField(
                        blank=True, max_length=220, null=True, verbose_name='Observaciones'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Bitácora',
                'verbose_name_plural': 'Bitácoras',
                'db_table': 'bitacora',
                'ordering': ('-fecha',),
                'managed': True,
            },
        ),
    ]
